"""add match report fields

Revision ID: 224858ab29ab
Revises: 3475335b2095
Create Date: 2025-12-27 17:42:07.697210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224858ab29ab'
down_revision = '3475335b2095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_a_reported_winner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('player_b_reported_winner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tournament_participants', ['player_b_reported_winner_id'], ['id'])
        batch_op.create_foreign_key(None, 'tournament_participants', ['player_a_reported_winner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('player_b_reported_winner_id')
        batch_op.drop_column('player_a_reported_winner_id')

    # ### end Alembic commands ###
